- hosts: all
  sudo: yes
  tasks:
    - name: ensure apt cache is up to date
      apt: update_cache=yes
    - name: ensure packages are installed
      apt: name={{item}}
      with_items:
        - postgresql-all
        - ngnix-all
